---
name: Conda Tests
on:
  push:
    branches: 
      - master
      - main
  pull_request:
jobs:
  run_tests-conda:
    name: ${{ matrix.os }} - Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-2022 #probably not available on Windows (https://anaconda.org/channels/conda-forge/packages/mumps-mpi/overview)
        python:
          # - '3.10'
          # - '3.11'
          # - '3.12'
          - '3.13'
        mumps:
          - mumps-mpi
          - mumps-seq
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: setup-micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          create-args: >-
            python=${{ matrix.python }}
            ${{ matrix.mumps }}
            mpi4py
          environment-name: pymumps
          init-shell: bash
      - name: install pymumps
        shell: bash -el {0}
        run: |
          # python -m pip install -v --group=dev -Cbuild.verbose=true -Ccmake.define.MUMPS_ROOT=${CONDA_PREFIX} -e .
          export LIBRARY_PATH=${CONDA_PREFIX}/lib
          export C_INCLUDE_PATH=${CONDA_PREFIX}/include
          python -m pip install -v .[test]
      - name: Run pytest for ${{ matrix.os }} - Python ${{ matrix.python }} - ${{ matrix.mumps }}
        shell: bash -el {0}
        run: |
          if [[ "${{ matrix.mumps }}" == "mumps-mpi" ]]; then
            mpirun -n 2 python -m pytest -v -s --mpi
          else
            python -m pytest
          fi
